### ISSUE TITLE
links to checkpoint for all the rest of the tasks

### ISSUE THREAD

**Issue by Deepayan137** [showlab/CLVQA#5]
Hello,

I am reaching out to inquire if it might be possible to share the final checkpoints after each specific task within the sequence. Specifically, for the task order abbreviated as 'oarlks', could the checkpoints be made available after the fine-tuning stages of each task—object, attribute, relation, logic, and knowledge? Access to these checkpoints would be extremely valuable for my ongoing research and development work.

Thank you for considering this request. I look forward to your response.

Best regards,

**Comment by StanLei52** [comment]
Hi, thank you for your interest. I have uploaded all the checkpoints for `oarlks` to release. Specifically: [o.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/unicl_object_stand_alone.pth), [a.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/unicl_oarlks-a.pth), [r.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/unicl_oarlks-r.pth), [l.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/unicl_oarlks-l.pth), [k.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/unicl_oarlks-k.pth) and [s.ckpt](https://github.com/showlab/CLVQA/releases/download/v1.0/function_oarlks_distilgpt2_replay_qag_seq_not_use_gt_task_token_1.5_unicl_final.pth).

Since there are a lot of ckpts saved during experiments due to different task orders, if you need a specific order, feel free to specify the setting via issue or config the experiment setting to exec the code.

**Comment by Deepayan137** [comment]
Thank you so much for your prompt reply. This will be very helpful in my work.

**Comment by Deepayan137** [comment]
Hello authors, 

Can you please share the final checkpoints after each specific task for the sequences 'roslak' and 'lkosra '? We are comparing our method on these two sequences and it would be great if we could have the checkpoints to obtain the accuracy after each task.

TIA

**Comment by StanLei52** [comment]
Hi, I've uploaded the checkpoints to the [release](https://github.com/showlab/CLVQA/releases/tag/v1.0) of this repo. Note that the ckpt of the first task is ended with "standalone", and the rest you may find the task order in the file name.

**Comment by Deepayan137** [comment]
Thank you authors
